/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author seung
 */
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdk.internal.org.jline.terminal.TerminalBuilder;



public class NewJFrame extends javax.swing.JFrame {
    // DB_MAN 클래스의 인스턴스를 생성하여 데이터베이스 연결 관리를 수행
    DB_MAN DBM = new DB_MAN();
    String strSQL = "select * from user";
    
    // 1. CardLayout 인스턴스 생성 및 JFrame의 content pane에 설정
    private CardLayout cardLayout;
    
    public NewJFrame() {
        initComponents();
        
        // CardLayout 초기화 및 적용
        cardLayout = new CardLayout();
        getContentPane().setLayout(cardLayout);
        
        // 로그인 및 회원가입 버튼을 포함하는 초기 패널 생성
        JPanel initialPanel = new JPanel();
        initialPanel.add(btn_login);
        initialPanel.add(btn_sign);
        
        // 초기 패널을 CardLayout에 추가
         getContentPane().add(initialPanel, "InitialPanel");
        // 패널을 CardLayout에 추가
        getContentPane().add(loginPanel, "LoginPanel");
        getContentPane().add(signPanel, "SignPanel");
        
        // 첫 화면을 초기 패널로 설정
        cardLayout.show(getContentPane(), "InitialPanel");
        
        // btn_login 버튼에 액션 리스너 추가
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        // btn_sign 버튼에 액션 리스너 추가
        btn_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signActionPerformed(evt);
            }
        });
        
        
        try{
            String strData = null;
            DBM.dbOpen();// 데이터베이스 연결을 열고,
            getDBData(strSQL); // SQL 쿼리를 실행하여 데이터를 가져온다.
            DBM.dbClose();
        }catch(Exception e){
            System.out.println("NewJFrame.<init>()");
        }
        
        
    }
    
    // 데이터베이스에서 데이터를 가져와 JTextArea에 표시하는 메서드
    public final void getDBData(String strQuery) {
        String strOutput = "";

        try {
            // SQL 쿼리를 실행하고 결과를 DBM.DB_rs에 저장
            System.out.println(strQuery);
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
            
            while (DBM.DB_rs.next()) {
                strOutput = "";
                strOutput += DBM.DB_rs.getString("id") + "\t";
//                strOutput += DBM.DB_rs.getString("pw") + "\t";
//                strOutput += DBM.DB_rs.getString("name") + "\t";
//                strOutput += DBM.DB_rs.getString("birthd") + "\t";
            }
            DBM.DB_rs.close();
        } catch (Exception e) {
            System.out.println("SQLException: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signPanel = new javax.swing.JPanel();
        txt_pwcheck = new javax.swing.JPasswordField();
        lbl_hurdle4 = new javax.swing.JLabel();
        lbl_title1 = new javax.swing.JLabel();
        lbl_id1 = new javax.swing.JLabel();
        lbl_pw1 = new javax.swing.JLabel();
        lbl_hurdle1 = new javax.swing.JLabel();
        lbl_pwcheck1 = new javax.swing.JLabel();
        lbl_hurdle2 = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        btn_sign1 = new javax.swing.JButton();
        lbl_birth1 = new javax.swing.JLabel();
        btn_idcheck = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        lbl_hurdle3 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_pw = new javax.swing.JPasswordField();
        txt_birth = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        btn_login = new javax.swing.JButton();
        btn_sign = new javax.swing.JButton();

        txt_pwcheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pwcheckKeyReleased(evt);
            }
        });

        lbl_hurdle4.setForeground(new java.awt.Color(255, 51, 51));
        lbl_hurdle4.setText("8자리 입력");

        lbl_title1.setText("회원가입");

        lbl_id1.setText("아이디");

        lbl_pw1.setText("비밀번호");

        lbl_hurdle1.setForeground(new java.awt.Color(255, 51, 51));
        lbl_hurdle1.setText("영어 대문자, 소문자, 숫자, 특수문자를 조합해주세요.");

        lbl_pwcheck1.setText("비밀번호 확인");

        lbl_hurdle2.setForeground(new java.awt.Color(255, 51, 51));
        lbl_hurdle2.setText("8~15자 이상 입력");

        lbl_name1.setText("성명");

        btn_sign1.setText("회원가입");
        btn_sign1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign1ActionPerformed(evt);
            }
        });

        lbl_birth1.setText("생년월일");

        btn_idcheck.setText("중복 확인");
        btn_idcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idcheckActionPerformed(evt);
            }
        });

        lbl_hurdle3.setForeground(new java.awt.Color(255, 51, 51));
        lbl_hurdle3.setText("비밀번호가 일치하지 않습니다.");

        txt_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwActionPerformed(evt);
            }
        });
        txt_pw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pwKeyReleased(evt);
            }
        });

        txt_birth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_birthKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout signPanelLayout = new javax.swing.GroupLayout(signPanel);
        signPanel.setLayout(signPanelLayout);
        signPanelLayout.setHorizontalGroup(
            signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signPanelLayout.createSequentialGroup()
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signPanelLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(lbl_title1))
                    .addGroup(signPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signPanelLayout.createSequentialGroup()
                                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_id1)
                                    .addComponent(lbl_pw1)
                                    .addComponent(lbl_pwcheck1))
                                .addGap(61, 61, 61)
                                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_hurdle1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_hurdle2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_hurdle3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(signPanelLayout.createSequentialGroup()
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btn_idcheck))
                                    .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_pwcheck, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(txt_pw, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(signPanelLayout.createSequentialGroup()
                                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_name1)
                                    .addComponent(lbl_birth1))
                                .addGap(61, 61, 61)
                                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_hurdle4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(signPanelLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(btn_sign1)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        signPanelLayout.setVerticalGroup(
            signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_title1)
                .addGap(26, 26, 26)
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_idcheck))
                .addGap(28, 28, 28)
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pw1)
                    .addComponent(txt_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pwcheck1)
                    .addComponent(txt_pwcheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lbl_hurdle1)
                .addGap(18, 18, 18)
                .addComponent(lbl_hurdle2)
                .addGap(18, 18, 18)
                .addComponent(lbl_hurdle3)
                .addGap(12, 12, 12)
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_name1)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(signPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_birth1)
                    .addComponent(txt_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hurdle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sign1)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_login.setText("로그인");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_sign.setText("회원가입");
        btn_sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(btn_sign)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        cardLayout.show(getContentPane(), "LoginPanel");
    }//GEN-LAST:event_btn_loginActionPerformed

    
    private void txt_pwcheckKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwcheckKeyReleased
        if (String.valueOf(txt_pw.getPassword()).equals(String.valueOf(txt_pwcheck.getPassword())) ) {
            lbl_hurdle3.setForeground(new Color(0,204,102));    
        }
    }//GEN-LAST:event_txt_pwcheckKeyReleased

    private void btn_sign1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sign1ActionPerformed
            strSQL = "Insert Into user Values (";
            strSQL += "'" + txt_id.getText() + "', ";
            strSQL += "'" + txt_pwcheck.getText() + "', ";
            strSQL += "'" + txt_name.getText() + "', ";
            strSQL += "'" + txt_birth.getText() + "')";

            try {
                DBM.dbOpen();
                DBM.DB_stmt.executeUpdate(strSQL);
                strSQL = "Select * From user";
                getDBData(strSQL);
                JOptionPane.showMessageDialog(null, "회원가입 완료");
                DBM.dbClose();
            } catch (Exception e) {
                System.out.println("SQLException: " + e.getMessage());
            }
    }//GEN-LAST:event_btn_sign1ActionPerformed

    private void btn_idcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idcheckActionPerformed
        String ID = txt_id.getText();
        strSQL = "SELECT id FROM user WHERE id = '" + ID + "'";
        
        if(ID.contains(" ")){
            JOptionPane.showMessageDialog(null,"띄어쓰기는 불가능합니다.");
            return;
        }

        try {
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            
            // 만약 결과가 존재한다면 중복된 ID가 있다는 메시지를 표시
            if (DBM.DB_rs.next()) {
                JOptionPane.showMessageDialog(null, "이미 사용 중인 ID입니다. 다른 ID를 입력해주세요.");
            } else {
                JOptionPane.showMessageDialog(null, "사용 가능한 ID입니다.");
            }
            DBM.DB_rs.close();
            DBM.dbClose();
        } catch (Exception e) {
            System.out.println("SQLException: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_idcheckActionPerformed

    private void txt_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwActionPerformed
    
    private void txt_pwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwKeyReleased
        //String passwordPattern = "^(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]).*$";
        String passwordPattern = "^((?=.*[a-z])(?=.*\\d))";
        if(String.valueOf(txt_pw.getPassword()).length() >= 8){
            lbl_hurdle2.setForeground(new Color(0,204,102));
        }
        
        // 정규식 검사
        if (Pattern.matches(passwordPattern, String.valueOf(txt_pw.getPassword()))) {
            lbl_hurdle1.setForeground(new Color(0,204,102)); 
        } 
    }//GEN-LAST:event_txt_pwKeyReleased

    private void txt_birthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_birthKeyReleased
        String birth = txt_birth.getText();
        
        if (birth.length() > 8) {
        // 입력이 8자리를 초과하는 경우, 입력을 무시하고 이전 상태로 되돌립니다.
            txt_birth.setText(birth.substring(0, 8));     
        }
  
        if(birth.length() == 8){
            lbl_hurdle4.setForeground(new Color(0,204,102));
        }
    }//GEN-LAST:event_txt_birthKeyReleased

    private void btn_signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signActionPerformed
        cardLayout.show(getContentPane(), "SignPanel");
    }//GEN-LAST:event_btn_signActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_idcheck;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_sign;
    private javax.swing.JButton btn_sign1;
    private javax.swing.JLabel lbl_birth1;
    private javax.swing.JLabel lbl_hurdle1;
    private javax.swing.JLabel lbl_hurdle2;
    private javax.swing.JLabel lbl_hurdle3;
    private javax.swing.JLabel lbl_hurdle4;
    private javax.swing.JLabel lbl_id1;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_pw1;
    private javax.swing.JLabel lbl_pwcheck1;
    private javax.swing.JLabel lbl_title1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel signPanel;
    private javax.swing.JTextField txt_birth;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pw;
    private javax.swing.JPasswordField txt_pwcheck;
    // End of variables declaration//GEN-END:variables
}
